name: CI/CD da API de Jogos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE_NAME: brunolazzara/gameplatform-jogos-fiap

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar pacotes
      run: dotnet restore GamePlatform.Jogos.sln

    - name: Build
      run: dotnet build GamePlatform.Jogos.sln --configuration Release --no-restore

    - name: Testes
      run: dotnet test GamePlatform.Jogos.Tests/GamePlatform.Jogos.Tests.csproj --verbosity normal

  build-and-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          push: true

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy para o Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: 'gameplatform'
          containerAppName: 'gameplatform-jogos-api'
          image: 'brunolazzara/gameplatform-jogos-fiap'
